### ISSUE TITLE
Search Algorithm

### ISSUE THREAD

**Issue by blaine-wataru** [campusbeats/campusbeats#15]
Implement search on directory page.

**Comment by innikakp** [comment]
@blaine-wataru was able to fix the tags on cards to reflect various collections in database to help with the search algorithm

**Comment by innikakp** [comment]
In conjunction with this issue, issue #25 was fixed and closed. As such, cards with data from Profile collection show up on Beats page (the search page). Now able to see which cards will potentially be searched for

**Comment by innikakp** [comment]
Was able to get one field/form to work with filtering (e.g. Abilities). Will proceed to figuring out how to get all fields to filter together and will merge to this issue's branch when figured out

**Comment by innikakp** [comment]
@blaine-wataru was able to get the search algorithm working (to an extent) on drop downs. However, every option needs to be selected before one an search for a profile. May consider fixing this, but issue is currently fixed at this time.
