### ISSUE TITLE
Favorites / People Interested in You Controls

### ISSUE THREAD

**Issue by blaine-wataru** [campusbeats/campusbeats#18]

**Comment by innikakp** [comment]
Created FavoritesCollection, which show who is a part of a user's favorites, and was able to get the cards to reflect the data in the FavoritesCollection. Edited the initial collection to have sample data for the FavoritesCollection.

**Comment by innikakp** [comment]
Created PeopleInterestedCollection, which shows those who are interested in the user, and got the data from the collection to show on the cards. Edited the initial collection with sample data for the PeopleInterestedCollection.  Also edited the HTML and cards of Home and Admin pages with icons & the made headings of Admin page a little bigger.
