### ISSUE TITLE
Implement new UI Card Design

### ISSUE THREAD

**Issue by blaine-wataru** [campusbeats/campusbeats#28]
New UI card design

**Comment by innikakp** [comment]
Updated data Profile, Favorites, & PeopleInterested collections. Added more links for soundcloud, youtube, and spotify link for profiles

**Comment by innikakp** [comment]
Removed address field from Profile page and cards in Home & Admin pages reflect correct data from collections

**Comment by innikakp** [comment]
Updated card design to reflect different features

**Comment by innikakp** [comment]
Updated card design to reflect feature functionality
