### ISSUE TITLE
Monitor button functionality (frowny face button)

### ISSUE THREAD

**Issue by lancenhd** [campusbeats/campusbeats#38]
- Works similar to favorites button (star icon)
- When frowny face button is pressed on beats page, it collects that profile you clicked on and sends it to knew collection that isn't profile collection. 
- Shows user in monitor page the people who supposedly was reported for doing "bad stuff"

**Comment by innikakp** [comment]
Is a part of Admin Controls - Issue #17. Closing this out as it's implementing the same functionality
